feat(app): add QuestionsSidebar
typeofweb/devfaq pull request #392
Opened 2022-12-08 17:04 UTC by xStrixU

Fixes #386

2022-12-08 19:23 UTC, mmiszy requested changes

2022-12-08 19:23 UTC, mmiszy commented on apps/app/src/app/questions/page.tsx
> +const QuestionsPage = () => {
To chyba powinno być w layout.tsx i zamiast diva children

2022-12-08 19:23 UTC, mmiszy commented on apps/app/src/components/QuestionsSidebar/TechnologyFilter/TechnologyFilter.tsx
> +				<Technology title="Angular" icon={<AngularLoro />} />
```suggestion
				<Technology title="Angular" icon={<AngularLogo />} />
```

2022-12-08 19:23 UTC, mmiszy commented on apps/app/src/styles/variables.css
> +	--senior-main-color-light: #ffc83e;
Jeśli zamienimy te kolory na oklch to może okaże się, że można je wygenerować - tzn w oklch z jednego koloru łatwo stworzyć wersje light, dark i darker.

2022-12-09 11:21 UTC, mmiszy commented on apps/app/src/components/QuestionsSidebar/LevelFilter/LevelButton.tsx
> +		active: "level-button-active-shadows bg-junior-main hover:bg-junior-main-light",
`level-button-shadows` i `level-button-active-shadows` powtarzają się, może powinniśmy je umieścić w linijce 37-40?

2022-12-09 11:23 UTC, xStrixU commented on apps/app/src/components/QuestionsSidebar/LevelFilter/LevelButton.tsx
> +		active: "level-button-active-shadows bg-junior-main hover:bg-junior-main-light",
dobry pomysł!

2022-12-10 11:30 UTC, mmiszy approved these changes

2022-12-10 11:32 UTC, merged