fix(app): improve QuestionsSidebar styles
typeofweb/devfaq pull request #454
Opened 2022-12-21 20:05 UTC by grzegorzpokorski

2022-12-22 07:00 UTC, AdiPol1359 reviewed
Po zmianach zauważyłem problem z cieniami. Cienie ucinają się na krawędziach:
![Screenshot_2022-12-22-07-56-14-986_com android chrome](https://user-images.githubusercontent.com/27779154/209075881-56ebb373-7ff3-447b-ae71-7867504f8ebf.png)
![Screenshot_2022-12-22-07-56-27-621_com android chrome](https://user-images.githubusercontent.com/27779154/209075904-1af946c8-f16b-49b2-b2be-85c967b9ca55.png)

2022-12-22 08:36 UTC, mmiszy requested changes

2022-12-22 08:36 UTC, mmiszy commented on apps/app/src/components/QuestionsSidebar/QuestionsSidebar.tsx
> +				"fixed inset-0 z-50 flex shrink-0 -translate-x-full transform-gpu flex-col gap-y-6 overflow-y-auto bg-gray-50 px-2.5 py-6 pb-4 transition-transform duration-200 after:absolute after:top-0 after:b
Skąd `56px` ?

2022-12-22 08:39 UTC, mmiszy commented
@grzegorzpokorski  o dokładnie ma poprawiać ten PR? Nie widzę żadnych różnic poza popsutymi cieniami i brakiem oddzielenia od listy pytań
<img width="413" alt="Screenshot 2022-12-22 at 09 37 40" src="https://user-images.githubusercontent.com/1338731/209093277-a3d1d04f-23b1-4a6a-8071-3d7787b63447.png">

2022-12-22 11:21 UTC, grzegorzpokorski commented
@AdiPol1359 dzięki za zwrócenie uwagi! Postaram się poprawić cienie. @mmiszy pr poprawia responsywność, przykład niedoróbki na screenie, oraz eliminuje konieczność przewijania całej strony, gdy chcemy dostać się do opcji znajdujących się na końcu tego sidebara.
![Screenshot_20221222-121453](https://user-images.githubusercontent.com/27455716/209123561-a531224c-7956-4442-9e35-191197c7e8bb.jpg)

2022-12-22 16:51 UTC, grzegorzpokorski commented on apps/app/src/components/QuestionsSidebar/QuestionsSidebar.tsx
> +				"fixed inset-0 z-50 flex shrink-0 -translate-x-full transform-gpu flex-col gap-y-6 overflow-y-auto bg-gray-50 px-2.5 py-6 pb-4 transition-transform duration-200 after:absolute after:top-0 after:b
Stąd: `sm:top-[56px]`

2022-12-24 13:00 UTC, grzegorzpokorski commented
Prace kontynuuje w tym PR: #467

2022-12-24 13:00 UTC, closed without merging