feat(app): add skip to the content link
typeofweb/devfaq pull request #471
Opened 2022-12-24 19:03 UTC by grzegorzpokorski

PR improve accessibility by adding skip to the content link.

2022-12-24 19:17 UTC, grzegorzpokorski commented on apps/app/src/components/SkipToTheContent.tsx
> +	<a
I need confirmation that I used proper tag - I'm not sure that we can't achieve that functionality by using the `Link` from `next/link`.

When I wanted to use `Link` component from `next/link` I realized that when I click on a link which contains for eg. `#element` at the end of the href attribute it does not cause scrolling page to the pointed element so I used native html `a` tag which works as expected.

2022-12-26 00:22 UTC, grzegorzpokorski commented on apps/app/src/components/SkipToTheContent.tsx
> +	<a
I found something about my concerns: https://github.com/vercel/next.js/issues/44295

2022-12-31 12:57 UTC, mmiszy requested changes

2022-12-31 12:57 UTC, mmiszy commented on apps/app/src/components/SkipToTheContent.tsx
> +);
```suggestion
export const SkipToTheContent = () => {
	// @todo replace with `Link` when https://github.com/vercel/next.js/issues/44295 is fixed
	return (
		<a
			href={`#main-content`}
			className="fixed -top-[100%] z-50 m-4 border-white bg-violet-900 p-4 px-8 text-white focus:top-0 focus:border-2 focus:border-dashed"
		>
			Przejdź do treści
		</a>
	);
};
```

2022-12-31 13:27 UTC, mmiszy commented
Konflikty.

2022-12-31 13:52 UTC, mmiszy approved these changes

2022-12-31 13:52 UTC, merged