fix(app): Improve modals a11y
typeofweb/devfaq pull request #475
Opened 2023-01-03 00:30 UTC by grzegorzpokorski

2023-01-03 21:46 UTC, mmiszy requested changes
Teraz przycisk do otwierania menu na mobile jest przesunięty w lewo, a do zamykania w prawo – co powoduje niemiły efekt.

2023-01-04 14:13 UTC, grzegorzpokorski commented on apps/app/src/components/AddQuestionConfirmationModal.tsx
> +					Potwierdznie przekazania pytania do zatwierdzenia.
Tytuł w tym przypadku wnosi etykietę dla okna dialogowego jakim jest ten modal. Sugerując się poniższymi artykułami:

- https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/#name_calculation 
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal

uznałem, że dodanie tego tytułu sprawi, że modal będzie posiadał jednoznaczne 'accessible name'.

2023-01-04 14:43 UTC, grzegorzpokorski commented on apps/app/src/components/Header/HeaderNavigation.tsx
> +						: "absolute sm:hidden",
To jest dobre pytanie, bo na pierwszy rzut oka może być nie jasne po co je dodałem. Między innymi te style co wskazałeś mają za zadanie zapewnienie dostępności przycisku zamykającego menu z poziomu klawiatury. Do tej pory kiedy stron wyświetlana była w viewporcie o szerokości >= sm przycisk otwierania / zamykania menu był automatycznie ukrywany w sposób nieumożliwiający dostęp do niego za pomocą klawiatury. Stało się to problemem kiedy dodałem 'focus lock' do menu głównego. Dlaczego? Załóżmy taki scenariusz:
1. otwieram stronę na urządzeniu z szerokością viewportu < sm.

![1](https://user-images.githubusercontent.com/27455716/210578146-949e9670-11e3-4d9e-abfd-702e2db52ecf.png)

2. otwieram menu mobilne - w tym momencie focus jest uwięziony w tym menu.

![5](https://user-images.githubusercontent.com/27455716/210578508-541492ac-d9a4-4683-99ee-4bcaa1cd3673.png)
 
3. użytkownik zmienia rozmiar viewportu na >= sm - menu mobilne zmienia formę, ukrywany jest guzik zamykania menu mobilnego, lecz focus nadal jest uwięziony w menu.

![2](https://user-images.githubusercontent.com/27455716/210578722-7a04d875-5e30-4b2e-bddc-c66861d3de10.png)
 
4.  Aby uwolnić focus dodałem style, które pozwalają na dostęp do buttona zamykającego menu z poziomu klawiatury, który w tym przypadku pozwoli na uwolnienie focusa z menu.

![3](https://user-images.githubusercontent.com/27455716/210579066-63c1227d-77cc-4ba0-be5f-075b004e3691.png)

![4](https://user-images.githubusercontent.com/27455716/210579121-824c0e18-2f8d-4dbd-967f-125f309f1647.png)

2023-01-04 16:13 UTC, mmiszy commented on apps/app/src/components/Header/HeaderNavigation.tsx
> +						: "absolute sm:hidden",
Ten przycisk jest dostępny tylko z klawiatury, więc w jaki sposób użytkownicy myszki albo smartfona mają się do niego dostać?
Nie lepiej byłoby automatycznie zamykać menu gdy zmienia się rozmiar viewportu?

2023-01-04 16:18 UTC, grzegorzpokorski commented on apps/app/src/components/Header/HeaderNavigation.tsx
> +						: "absolute sm:hidden",
Użytkownicy myszki czy smartfonu nie muszą mieć do niego dostępu :) Rozwiązanie jest przygotowane tylko dal użytkowników czytników ekranowych. Ktoś kto korzysta z myszki czy ekranu dotykowego nie ma ograniczonego dostępu do elementów znajdujących się na stronie.

2023-01-04 16:24 UTC, grzegorzpokorski commented on apps/app/src/components/Header/HeaderNavigation.tsx
> +						: "absolute sm:hidden",
> Nie lepiej byłoby automatycznie zamykać menu gdy zmienia się rozmiar viewportu?

Rozwiązało by wiele problemów, min. ten o którym rozmawiamy. Pytanie czy nie wpłynie to negatywnie na wydajność, czy raczej na tym etapie nie ma się co tym przejmować?

2023-01-04 16:26 UTC, mmiszy commented on apps/app/src/components/Header/HeaderNavigation.tsx
> +						: "absolute sm:hidden",
> Użytkownicy myszki czy smartfonu nie muszą mieć do niego dostępu :)

Dlaczego nie?

> Ktoś kto korzysta z myszki czy ekranu dotykowego nie ma ograniczonego dostępu do elementów znajdujących się na stronie.

Oczywiście, że ma – nie może sfocusować niczego innego.

2023-01-04 19:59 UTC, grzegorzpokorski commented
Z powodu diametralnej zminay koncepcji, jak rozwiązać niektóre problemy wskazane w tym PR postanowiłem każdym z tych problemów zająć się w oddzielnym PR 🙂

2023-01-04 19:59 UTC, closed without merging